geoarrow/geoarrow-c

.clang-format
.github/workflows/build-and-test.yaml
.gitignore
CMakeLists.txt
CMakePresets.json
CMakeUserPresets.json.example
src/geoarrow/geoarrow.h
src/geoarrow/geoarrow_arrow.hpp
src/geoarrow/geoarrow_arrow_test.cc
src/geoarrow/geoarrow_type.h
src/geoarrow/nanoarrow.c
src/geoarrow/nanoarrow.h
src/geoarrow/schema.c
src/geoarrow/schema_test.cc
src/geoarrow/schema_view.c
src/geoarrow/schema_view_test.cc
valgrind.supp

This PR implements:
- A general repository structure with CMakeLists + GitHub Actions that runs tests, test coverage, and valgrind
- A set of functions and types that create, consume, and validate `struct ArrowSchema` representations of GeoArrow data types according to the extension.md and format.md (as proposed in https://github.com/geoarrow/geoarrow/pull/26)
- A header for those with access to Arrow C++ that implements the `ExtensionType` subclass for these objects.
The general approach was to have a few `enum`s representing concepts in the format spec:
- `enum GeoArrowType`: one entry per unique memory layout. With multiple coordinate types there are a lot of these. Maybe `GeoArrowLayout` might be a better name for this.
- `enum GeoArrowGeometryType`: geometry, point, linestring, …

Initial implementation of GeoArrow memory layout + extension types

---

src/geoarrow/schema.c
src/geoarrow/schema_test.cc

Inspired by https://github.com/geoarrow/geoarrow/pull/30 and https://github.com/geoarrow/geoarrow/pull/31, since I realized I was generating incorrect names!

Generate types with the correct child names

---

python/geoarrow/pyarrow.py
python/tests/test_geoarrow_pyarrow.py
src/geoarrow/geoarrow.h
src/geoarrow/kernel.c
src/geoarrow/kernel_test.cc
src/geoarrow/wkt_writer.c
src/geoarrow/wkt_writer_test.cc

To avoid hanging whist printing very large geometries.

Support max_element_size_bytes in wkt writer

---

python/geoarrow/pyarrow.py
python/tests/test_geoarrow_pyarrow.py
src/geoarrow/kernel.c
src/geoarrow/kernel_test.cc

This is needed for geoarrow conversion: it scans WKT and WKB in a sufficiently lazy way so we can figure out what geoarrow type is appropriate.

Add unique geometry types aggregator

---

src/geoarrow/builder.c
src/geoarrow/kernel.c

Mostly just one hack that prevented `GeoArrowBuilderFinish()` from being called more than once.

Clean up hacks in the GeoArrowBuilder 

---

CMakeLists.txt
src/geoarrow/array_view.c
src/geoarrow/builder.c
src/geoarrow/geoarrow.h
src/geoarrow/kernel.c
src/geoarrow/metadata.c
src/geoarrow/util.c
src/geoarrow/util_test.cc
src/geoarrow/wkb_reader.c
src/geoarrow/wkt_reader.c
src/geoarrow/wkt_writer.c

Provide our own GeoArrowErrorSet() for GeoArrowError to minimize the number of times we have to cast between error types.

Clean up ArrowErrorSet() usage

---

python/geoarrow/pyarrow/__init__.py
python/geoarrow/pyarrow/_compute.py
python/tests/test_geoarrow_pyarrow_compute.py

Sometimes you just need x and y!
```
>>> import geoarrow.pyarrow as ga
>>> x, y = ga.point_coords(["POINT (0 1)", "POINT (2 3)"])
>>> list(x)
[<pyarrow.DoubleScalar: 0.0>, <pyarrow.DoubleScalar: 2.0>]
>>> list(y)
[<pyarrow.DoubleScalar: 1.0>, <pyarrow.DoubleScalar: 3.0>]
```

Add `point_coords()` to Python bindings

---

.github/workflows/python.yaml
python/pyproject.toml

...just for now. Tests pass with cython 3.0.0 on MacOS but not Linux apparently.

Set upper pin on cython

---

python/geoarrow/pandas.py
python/geoarrow/pyarrow/__init__.py
python/geoarrow/pyarrow/_array.py
python/geoarrow/pyarrow/_type.py
python/pyproject.toml
python/tests/test_geoarrow_pandas.py
python/tests/test_geoarrow_pandas_suite.py
python/tests/test_geoarrow_pyarrow.py

Adds:
- A `geoarrow` Series accessor (e.g., `df.geometry.geoarrow.with_crs("EPSG:4386")`). This will work for any Series that is string (interpreted as WKT) bytes (interpreted as WKB) or "geoarrow".
- A sparsely implemented "geoarrow" dtype/ExtensionArray. Currently backed by a `pyarrow.Array` or `pyarrow.ChunkedArray` but could in theory be backed by a C ArrowArray.
And, critically,
- The missing pieces required for that implementation
```python
import geoarrow.pandas
import pandas as pd
df = pd.read_parquet(
"https://github.com/geoarrow/geoarrow-data/releases/download/latest-dev/ns-water-basin_line-wkb.parquet"
)
df.geometry[0]
#> GeoArrowExtensionScalar("LINESTRING (648686.2 50...")
```

Sketch pandas integration

---

python/geoarrow/pyarrow/_dataset.py
python/tests/test_geoarrow_dataset.py

...works with overature! (Although sort of useless since its row groups are not spatially ordered)
```python
import geoarrow.pyarrow as ga
uri = "s3://overturemaps-us-west-2/release/2023-07-26-alpha.0/theme=admins"
ds = ga.dataset(uri, geometry_columns=["geometry"])
ds.index_fragments()
```

Fix GeoDataset for non-extension type column (e.g., overature)

---

CMakeLists.txt

This causes problems when using with other projects that also define `coverage_config` (notably, nanoarrow).

fix: Don't add coverage lib unless building tests

---

.gitignore
src/geoarrow/metadata.c
src/geoarrow/metadata_test.cc

Uncovered by https://github.com/geoarrow/geoarrow-r/issues/34 !
Basically, because we did a `break` instead of `return EINVAL`, we exposed uninitialized memory which (sometimes) caused a crash.
I also added the ability to treat edges/crs as `null` as identical to missing (even though it's technically not valid).

fix: Crash when metadata contains value with type that is not a list, object, or string

---

src/geoarrow/geoarrow_arrow.hpp
src/geoarrow/schema.c

Apparently Arrow C++ will throw an exception if you register an extension type with metadata but attempt to create an instance *without* metadata.

chore: Always export extension metadata

---

.github/workflows/python.yaml
python/geoarrow-c/tests/test_geoarrow_lib.py
src/geoarrow/schema.c
src/geoarrow/schema_test.cc

This aligns geoarrow-c with geoarrow-rs and the geoarrow implementation in the forthcoming geopandas!
This is a huge breaking change in the sense that it causes a lot of tests to fail in geoarrow-pyarrow; however, it is not much of a breaking change in the sense that the implementations here never check the nullability flag on import (and geoarrow-pyarrow defers to them almost everywhere).

fix!: Generate child fields as non-nullable

---

src/geoarrow/metadata.c

Found by the CRAN check: https://www.stats.ox.ac.uk/pub/bdr/memtests/gcc-UBSAN/geoarrow/tests/testthat.Rout
```
geoarrow.c:4843:7: runtime error: null pointer passed as argument 1, which is declared to never be null
#0 0x7f0fcf929ecf in GeoArrowUnescapeCrs /data/gannet/ripley/R/packages/tests-gcc-SAN/geoarrow/src/geoarrow.c:4843
#1 0x7f0fcf9e453b in geoarrow_c_schema_parse /data/gannet/ripley/R/packages/tests-gcc-SAN/geoarrow/src/r-type.c:82
#2 0x58c2e5 in R_doDotCall /data/gannet/ripley/R/svn/R-devel/src/main/dotcode.c:757
#3 0x652927 in bcEval_loop /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:8690
#4 0x68d632 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7523
```

fix: Fix passing NULL to memcpy when unescaping a CRS value

---

src/geoarrow/array_writer.c
src/geoarrow/array_writer_test.cc
src/geoarrow/geoarrow.h

Needed to ensure users can pass this value through!
https://github.com/paleolimbot/s2geography/pull/30/files#r1817306002

feat: Allow precision to be set in GeoArrowArrayWriter

---

src/geoarrow/array_reader.c
src/geoarrow/array_reader_test.cc
src/geoarrow/geoarrow.h
src/geoarrow/kernel.c

The `GeoArrowArrayReader()` is the easiest point of entry for reading "any geometry" via the visitor, even if a more efficient mechanism to read an array might exist. To reduce the scope of the `GeoArrowArrayView`, this PR moves the internals to be opaque with respect to array storage so that it can do things like read unions, dictionary-encoded, run-end encoded, or view-encoded versions of arrays (even though this implementation won't produce those types of arrays).

refactor: Make GeoArrowArrayReader more self-contained

---

CMakePresets.json
python/geoarrow-c/src/geoarrow/c/_lib.pyx
python/geoarrow-c/src/geoarrow/c/lib.py
src/geoarrow/geoarrow.h
src/geoarrow/geoarrow_type.h
src/geoarrow/geoarrow_type_inline.h
src/geoarrow/metadata.c
src/geoarrow/metadata_test.cc

This PR add support for the `crs_type` key that was added in recent PRs to the GeoArrow spec. We already had a `GeoArrowCrsType` enum which simplifies things considerably; however, we'd been guessing its value from the first character of the CRS. In this PR we stop doing that but parse the value of `crs_type` and pass it on.
In doing this, I also improved the serialization and deserialization code, added a canonical "lonlat" setter, and generally improved the tests for metadata serialization/deserialization.

feat: Support crs_type values in most recent spec release candidate

---

CMakeLists.txt
src/geoarrow/geoarrow.hpp
src/geoarrow/hpp/array_util.hpp
src/geoarrow/hpp/geometry_type_traits.hpp
src/geoarrow/hpp/geometry_type_traits_test.cc
src/geoarrow/hpp/wkb_util.hpp
src/geoarrow/hpp/wkb_util_test.cc

This PR makes it possible to write code against (compile-time) resolved Array classes
```c
using BoxXYZM = geoarrow::array_util::BoxXYZM<double>;
using XYZM = BoxXYZM::bound_type;
template <typename Array>
void GenericBoundsXYZM(Array& array, const struct GeoArrowArrayView* array_view,
BoxXYZM* out) {
array.Init(array_view);
BoxXYZM bounds = *out;
array.template VisitVertices<XYZM>([&](XYZM xyzm) {
for (size_t i = 0; i < xyzm.size(); i++) {
bounds[i] = std::min(bounds[i], xyzm[i]);
bounds[xyzm.size() + i] = std::max(bounds[xyzm.size() + i], xyzm[i]);
}
});
*out = bounds;
}
```
...followed by something like:
```c
GEOARROW_DISPATCH_ARRAY_CALL(type_id, GenericBoundsXYZM, reader.View().array_view(),
&bounds);
```
...which instantiates all the necessary templates. Probably this is …

feat: Add type traits to help resolve array and coordinate data types

---

src/geoarrow/hpp/array_reader.hpp

The non-const ownership-taking version is great, but libraries that don't have to give up ownership can use the interface more effectively if we expose not taking ownership (e.g., to present a view of some existing structure).

feat: Add `const ArrowArray` overload for `ArrayReader::SetArray()`

---

dev/benchmarks/c/wkb_bounding_benchmark.cc

This PR adds benchmarks for iterating over WKB end members using the new GeoArrowWKBReader + Geometry.
```
----------------------------------------------------------------------------------------------------
Benchmark                                          Time             CPU   Iterations UserCounters...
----------------------------------------------------------------------------------------------------
BenchBoundDoubles                             891823 ns       891731 ns          783 items_per_second=1.12142G/s
BenchBoundWKBLinestringUsingGeoArrowHpp       903941 ns       903838 ns          773 items_per_second=1.10639G/s
BenchBoundWKBPointsUsingGeoArrowHpp          6257939 ns      6256452 ns          115 items_per_second=159.835M/s
BenchBoundWKBLinestringUsingWkbReader …
```

chore: Add GeoArrowGeometry to benchmarks

---

.github/workflows/python.yaml
python/geoarrow-c/pyproject.toml
python/geoarrow-c/setup.py
python/geoarrow-c/src/geoarrow/c/_lib.pyx
python/geoarrow-c/src/geoarrow/c/lib.py
src/geoarrow/geoarrow_type.h
src/geoarrow/geoarrow_type_inline.h
src/geoarrow/metadata.c
src/geoarrow/metadata_test.cc

Adds the new edge types to the accepted list to ensure these don't error when passed to the parser and can roundtrip.
Also pins the Cython version for now...it's likely we'll move to nanobind rather than update the bindings for this for the next release.

feat: Add new edge types in GeoArrow 0.2 spec to C library

---

dev/benchmarks/c/wkb_bounding_benchmark.cc
src/geoarrow/builder.c
src/geoarrow/kernel.c

There were a few checks that prevented large/view types from being used in the kernels (even though the underlying reader supported them).

fix: Ensure large/view types can be used as input to kernels
